# Generated by Django 5.2.5 on 2025-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishresult',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
